apiVersion: apps/v1
kind: Deployment
metadata:
  name: pear-webfe-deployment
  labels:
    app: pear-webfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pear-webfe
  template:
    metadata:
      labels:
        app: pear-webfe
    spec:
      containers:
        - name: pear-webfe
          image: host.minikube.internal:5000/pear_webfe
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pear-webfe-service
spec:
  type: NodePort
  selector:
    app: pear-webfe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
