name: Playwright Tests
on:
  push:
    branches: [ main, test_edit_account/owen ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: [self-hosted, Linux, x64, webfe, staging]
    environment: test-staging

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Write test.env file
      run: echo "${{ secrets.TEST_ENV_FILE }}" > ./tests/e2e/test.env

    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
